### ISSUE TITLE
Floating point exception :(

### ISSUE THREAD

**Issue by jpihl** [nestorjhernandezm/mastermind-game#1]
Hi @nestorjhernandezm 

I got a floating point exception when trying to play a game:
```
Welcome to Mastermind!
For the instructions, please check the first comment from main.cpp
Introduce maximum number of trials (integer)
10
Introduce the code length (integer)
7
Do you want to repeat colors in a code? (Yes: 1, No: 0)
0
Floating point exception (core dumped)
```

Happy coding! :+1:

**Comment by nestorjhernandezm** [comment]
Hi @jpihl 

Thanks for the catch! Happy to see your comments after a big while. 🙂 

Ok, there is a maximum for the number of peg colors which is 6. I included a debugging print to indicate this now after remembering this little project :)

Try it again with 6 as code length or less instead of 7 (default is 4) and let me know it goes.

Happy testing! 😛🙂

**Comment by nestorjhernandezm** [comment]
Hi @jpihl ,

Did you have a chance to test the code with up to 6 peg colors? To see if I can close the issue 😉

**Comment by jpihl** [comment]
Sure :) with 6 or less it works fine 😎👍
